apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: carservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prakashsp23/cdac-project-manifest.git
    path: k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: carservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
